name: CI

on:
  workflow_call:
    secrets:
      COMPOSER_ACCESS_TOKEN:
        required: true

jobs:
  fix:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, redis, zip
          coverage: none
      - name: Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"
      - name: Install Dependencies
        uses: ramsey/composer-install@v2
      - name: Run linter
        run: vendor/bin/php-cs-fixer fix --config ruleset-phpcsfixer.php --show-progress=dots -vvv
#      - name: Commit changes
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "style: apply php-cs-fixer changes"

  analyze:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, redis, zip
          coverage: none
      - name: Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"
      - name: Install Dependencies
        uses: ramsey/composer-install@v2
      - name: Run analyzer
        run: vendor/bin/phpstan analyse --memory-limit=1G -c ruleset-phpstan.neon --error-format=github -vvv

  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, redis, zip
          coverage: none
      - name: Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"
      - name: Install Dependencies
        uses: ramsey/composer-install@v2
      - name: Run tests
        run: vendor/bin/phpunit -vvv
