name: CI

on:
  workflow_call:
    secrets:
      COMPOSER_ACCESS_TOKEN:
        required: true

jobs:
  duplication-check:
    name: Code duplication check
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: phpcpd

      - name: 🔧 Check code duplication in "src" directory
        run: phpcpd src/ --min-lines=6


  cs-fixer:
    name: PHP-CS-Fixer Linting
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: php-cs-fixer

      - name: 🔧  Run linter
        run: php-cs-fixer fix --dry-run --config ruleset-phpcsfixer.php --show-progress=dots -vvv


  analyze:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: 🧙 Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"

      - name: 🧙 Install Dependencies
        uses: ramsey/composer-install@v2
        #        https://github.com/sebastianbergmann/phpcpd/blob/21158aed508ffa2480b90f2af93724e3355c703f/.github/workflows/ci.yml#L58

      - name: Generate ide-helper files
        run: |
          if ${{env.DISABLE_IDE_HELPER}} == false; then
            composer eli:ide-helper
          fi

      - name: 🔧 Run analyzer
        run: vendor/bin/phpstan analyse --memory-limit=1G -c ruleset-phpstan.neon --error-format=github -vvv

  security-check:
    name: Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: Cache the vulnerability database
        uses: actions/cache@v3
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: 💩 Run security check
        uses: symfonycorp/security-checker-action@v3
        with:
          disable-exit-code: 1


  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🧙 Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"

      - name: 🧙 Install Dependencies
        uses: ramsey/composer-install@v2

      - name: 🔧 Run tests
#        run: vendor/bin/phpunit -vvv
        run: vendor/bin/testbench package:test --coverage --min=85
